// Auto-generated deployment configuration
// Do not edit this file directly. Edit public/config/deployment.json instead.

export const deploymentConfig = {
  mode: 'local',
  useWindowLocation: false,
  useNavigate: true,
} as const;

export type DeploymentMode = typeof deploymentConfig.mode;
