// Auto-generated deployment configuration
// Do not edit this file directly. Edit public/config/deployment.json instead.

export const deploymentConfig = {
  mode: 'edgeone',
  useWindowLocation: true,
  useNavigate: false,
} as const;

export type DeploymentMode = typeof deploymentConfig.mode;
