// Auto-generated security configuration
// This file is generated by scripts/generate-security-config.js
// Do not edit this file directly

export const securityConfig = {
  debugProtection: {
    enabled: true,
    disableF12: true,
    disableDevToolsShortcuts: true,
    disableViewSource: true,
    disableContextMenu: true,
    disableDrag: true,
    disableSelect: false,
    detectDevTools: true
  }
} as const;
