'use client';

/**
 * LanguageStatsWidget — displays repository language distribution as a donut chart.
 *
 * The center shows the largest language by default and switches to the hovered
 * language. Stats are generated by scripts/calculate-language-stats.js and synced
 * to public/data/language-stats.json during the build.
 */

import { useEffect, useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import { Code2 } from 'lucide-react';
import { useTranslation, useAnimationEnabled } from '@/hooks';

interface LanguageStat {
  name: string;
  color: string;
  lines: number;
  percentage: number;
}

interface LanguageStatsData {
  generatedAt: string;
  totalLines: number;
  languages: LanguageStat[];
}

export function LanguageStatsWidget() {
  const { t } = useTranslation();
  const animationEnabled = useAnimationEnabled();
  const [data, setData] = useState<LanguageStatsData | null>(null);
  const [hovered, setHovered] = useState<string | null>(null);

  useEffect(() => {
    fetch('/data/language-stats.json')
      .then((res) => res.json())
      .then((json: LanguageStatsData) => setData(json))
      .catch((error) => console.error('Failed to load language stats:', error));
  }, []);

  const activeLanguage = useMemo(() => {
    if (!data) return null;
    if (hovered) return data.languages.find((l) => l.name === hovered) || data.languages[0];
    return data.languages[0] || null;
  }, [data, hovered]);

  const segments = useMemo(() => {
    if (!data || data.languages.length === 0) return [];
    const radius = 36;
    const circumference = 2 * Math.PI * radius;
    let offset = 0;
    return data.languages.map((lang) => {
      const length = (lang.percentage / 100) * circumference;
      const segment = {
        ...lang,
        radius,
        circumference,
        length,
        offset,
      };
      offset -= length;
      return segment;
    });
  }, [data]);

  return (
    <motion.div
      initial={animationEnabled ? { opacity: 0, y: 16 } : undefined}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.4 }}
      className="h-full min-h-[220px] p-5 border-2 flex flex-col"
      style={{
        background: 'var(--bg-secondary)',
        borderColor: 'var(--border-subtle)',
        boxShadow: '4px 4px 0 var(--border-subtle)',
      }}
    >
      <div className="flex items-center gap-2 mb-4">
        <Code2 className="w-4 h-4" style={{ color: 'var(--accent-tertiary)' }} />
        <span className="text-xs font-mono uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>
          {t.widgets.languageStats}
        </span>
      </div>

      <div className="flex-1 flex flex-col items-center justify-center">
        {!data || data.languages.length === 0 ? (
          <span className="text-xs" style={{ color: 'var(--text-muted)' }}>
            {t.common.loading}
          </span>
        ) : (
          <>
            <div className="relative w-40 h-40">
              <svg viewBox="0 0 100 100" className="w-full h-full -rotate-90">
                {segments.map((segment) => (
                  <circle
                    key={segment.name}
                    cx="50"
                    cy="50"
                    r={segment.radius}
                    fill="none"
                    stroke={segment.color}
                    strokeWidth="18"
                    strokeLinecap="butt"
                    strokeDasharray={`${segment.length} ${segment.circumference - segment.length}`}
                    strokeDashoffset={segment.offset}
                    className="transition-opacity duration-200 cursor-pointer"
                    style={{
                      opacity: hovered && hovered !== segment.name ? 0.35 : 1,
                    }}
                    onMouseEnter={() => setHovered(segment.name)}
                    onMouseLeave={() => setHovered(null)}
                  />
                ))}
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                {activeLanguage ? (
                  <>
                    <span
                      className="text-lg font-bold uppercase"
                      style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-pixel)' }}
                    >
                      {activeLanguage.percentage.toFixed(1)}%
                    </span>
                    <span
                      className="text-[10px] font-mono uppercase tracking-wider"
                      style={{ color: 'var(--text-muted)' }}
                    >
                      {activeLanguage.name}
                    </span>
                  </>
                ) : null}
              </div>
            </div>

            <div className="flex flex-wrap justify-center gap-x-3 gap-y-1.5 mt-4">
              {data.languages.map((lang) => (
                <button
                  key={lang.name}
                  onMouseEnter={() => setHovered(lang.name)}
                  onMouseLeave={() => setHovered(null)}
                  className="flex items-center gap-1.5 text-[10px] font-mono uppercase transition-opacity hover:opacity-70"
                  style={{ color: 'var(--text-secondary)' }}
                >
                  <span
                    className="w-2 h-2 border border-[var(--border-subtle)]"
                    style={{ background: lang.color }}
                  />
                  {lang.name}
                </button>
              ))}
            </div>
          </>
        )}
      </div>
    </motion.div>
  );
}
